version: '3'

services:
  app:
    image: ansible-catalog:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - "./:/app:z"
    environment:
      - DJANGO_SETTINGS_MODULE=ansible_catalog.settings.development
      - CATALOG_LOG_ROOT=/app
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  worker:
    image: ansible-catalog:dev
    environment:
      - DJANGO_SETTINGS_MODULE=ansible_catalog.settings.development
      - CATALOG_LOG_ROOT=/app
      - OBJ_DISABLE_INITIALIZE_FORK_SAFETY=YES
    volumes:
      - "./:/app:z"
    depends_on:
      - app
      - redis
    command: python manage.py rqworker default
        