version: '3.9'

services:
  frontend:
    image: ansible-catalog-ui:dev
    build:
      context: frontend/
    depends_on:
      - app

  app:
    image: ansible-catalog:dev
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
    depends_on:
      - keycloak-setup
      - postgres

  # TODO: remove ansible-playbook from app image and use specific image for keycloak setup (affects minikube env)
  keycloak-setup:
    image: ansible-catalog:dev
    depends_on:
      - keycloak-app
    command: /opt/app-root/src/tools/docker/scripts/keycloak-setup.sh

  worker:
    image: ansible-catalog:dev
    depends_on:
      - app
      - redis
      - keycloak-setup
    command: /opt/app-root/src/tools/docker/scripts/worker.sh

  scheduler:
    image: ansible-catalog:dev
    depends_on:
      - app
      - redis
      - keycloak-setup
    command: "python manage.py cronjobs"

  keycloak-app:
    image: 'quay.io/keycloak/keycloak:15.0.2'
    depends_on:
      - 'postgres'

  redis:
    image: "docker.io/redis:alpine"

  postgres:
    image: 'docker.io/postgres:13-alpine'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_MULTIPLE_DATABASES=keycloak,catalog'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
      - "../docker/initdb:/docker-entrypoint-initdb.d:z"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  pg_data: {}
